import { db, GuestBook } from "astro:db";

// https://astro.build/db/seed
export default async function seed() {
  await db.insert(GuestBook).values([
    {
      author: "Alice Johnson",
      link: "https://alice.dev",
      content: "Love your work, keep it up!",
      country: "United States",
    },
    {
      author: "Ravi Kumar",
      link: "https://rkumar.blog",
      content: "Very interesting guestbook concept!",
      country: "India",
    },
    {
      author: "Li Wei",
      link: "",
      content: "Greetings from China!",
      country: "China",
    },
    {
      author: "Bob Smith",
      link: "",
      content: "Just dropping by to say hi!",
      country: "United Kingdom",
    },
    {
      author: "Gideon",
      link: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      content: "This is so cool!",
      country: "Canada",
    },
    {
      author: "Frank Miller",
      link: "",
      content: "This guestbook idea is awesome!",
      country: "Germany",
    },
    {
      author: "Isabella Rossi",
      link: "https://isabellar.com",
      content: "Amazing job from Brazil!",
      country: "Brazil",
    },
    {
      author: "Eva Williams",
      link: "https://evaw.design",
      content: "As a designer, I really appreciate the aesthetics here.",
      country: "France",
    },
    {
      author: "Olga Petrova",
      link: "",
      content: "Nice website design from Russia.",
      country: "Russia",
    },
    {
      author: "Charlie Adams",
      link: "https://charlieadams.blog",
      content: "Great site from Down Under!",
      country: "Australia",
    },
    {
      author: "Carlos Garcia",
      link: "https://cgarcia.mx",
      content: "Saludos desde México!",
      country: "Mexico",
    },
    {
      author: "Kenji Tanaka",
      link: "https://ktanaka.jp",
      content: "Inspiring work from Japan!",
      country: "Japan",
    },
    {
      author: "Maria Santos",
      link: "",
      content: "Visiting from the Philippines!",
      country: "Philippines",
    },
    {
      author: "Budi Hartono",
      link: "https://budi.id",
      content: "Keep up the great work!",
      country: "Indonesia",
    },
    {
      author: "Marco Rossi",
      link: "",
      content: "Ciao! Love the guestbook.",
      country: "Italy",
    },
    {
      author: "David Umoru",
      link: "https://davidumoru.me",
      content: "Hey, welcome to my guestbook!",
      country: "Nigeria",
    },
    {
      author: "Ahmed Khan",
      link: "https://akhan.pk",
      content: "Greetings from Pakistan!",
      country: "Pakistan",
    },
    {
      author: "Ayse Yilmaz",
      link: "",
      content: "Merhaba from Turkey!",
      country: "Turkey",
    },
    {
      author: "Grace Lee",
      link: "https://gracecodes.dev",
      content: "Nice work! Looking forward to more updates from South Korea.",
      country: "South Korea",
    },
    {
      author: "Sofia Lopez",
      link: "https://slopez.es",
      content: "Hola! Impressive site from Spain.",
      country: "Spain",
    },
    {
      author: "Jan Jansen",
      link: "",
      content: "Groeten uit Nederland!",
      country: "Netherlands",
    },
    {
      author: "Thabo Muller",
      link: "https://tmuller.za",
      content: "Cool guestbook feature from South Africa!",
      country: "South Africa",
    },
    {
      author: "Nguyen Van An",
      link: "",
      content: "Xin chào from Vietnam!",
      country: "Vietnam",
    },
    {
      author: "Fatima Ali",
      link: "https://fali.eg",
      content: "Visiting from Egypt.",
      country: "Egypt",
    },
    {
      author: "Rahim Ahmed",
      link: "",
      content: "Good job on the site from Bangladesh.",
      country: "Bangladesh",
    },
    {
      author: "Ivan Ivanov",
      link: "https://ivanov.ua",
      content: "Sending support from Ukraine!",
      country: "Ukraine",
    },
    {
      author: "Abdullah Al-Fahad",
      link: "",
      content: "Salam from Saudi Arabia!",
      country: "Saudi Arabia",
    },
    {
      author: "Maria Fernandez",
      link: "https://mfernandez.ar",
      content: "Interesting project from Argentina!",
      country: "Argentina",
    },
    {
      author: "Piotr Nowak",
      link: "",
      content: "Cześć! Nice guestbook from Poland.",
      country: "Poland",
    },
    {
      author: "Siti Aminah",
      link: "https://siti.my",
      content: "Great to see projects like this from Malaysia!",
      country: "Malaysia",
    },
    {
      author: "Visitor From Norway",
      link: "",
      content: "Beautiful design, greetings from Norway!",
      country: "Norway",
    },
    {
      author: "Island Visitor",
      link: "https://example.com/turksandcaicos",
      content: "Lovely guestbook! - Turks and Caicos",
      country: "Turks and Caicos",
    },
    {
      author: "Seychelles Guest",
      link: "",
      content: "Signing in from Seychelles!",
      country: "Seychelles",
    },
    {
      author: "Croatian Friend",
      link: "https://example.com/croatia",
      content: "Pozdrav iz Hrvatske! (Greetings from Croatia!)",
      country: "Croatia",
    },
    {
      author: "Portuguese Explorer",
      link: "",
      content: "Olá! Great site.",
      country: "Portugal",
    },
    {
      author: "Swedish Supporter",
      link: "https://example.com/sweden",
      content: "Hej från Sverige!",
      country: "Sweden",
    },
    {
      author: "Moroccan Traveler",
      link: "",
      content: "Greetings from Morocco.",
      country: "Morocco",
    },
    {
      author: "Colombian Connection",
      link: "https://example.com/colombia",
      content: "Saludos desde Colombia!",
      country: "Colombia",
    },
    {
      author: "Chilean Observer",
      link: "",
      content: "Hola from Chile!",
      country: "Chile",
    },
    {
      author: "Irish Visitor",
      link: "https://example.com/ireland",
      content: "Top o' the mornin'! Nice guestbook.",
      country: "Ireland",
    },
    {
      author: "Mauritius Fan",
      link: "",
      content: "Visiting from Mauritius!",
      country: "Mauritius",
    },
    {
      author: "Swiss Guest",
      link: "https://example.com/switzerland",
      content: "Grüezi! Signing from Switzerland.",
      country: "Switzerland",
    },
    {
      author: "Cameroon Explorer",
      link: "https://example.com/cameroon",
      content: "Bonjour! Signing in from Cameroon.",
      country: "Cameroon",
    },
    {
      author: "Safari Enthusiast",
      link: "",
      content: "Jambo! Greetings from beautiful Kenya.",
      country: "Kenya",
    },
    {
      author: "Accra Visitor",
      link: "https://example.com/ghana",
      content: "Akwaaba! Enjoying my time in Ghana.",
      country: "Ghana",
    },
    {
      author: "Lalibela Admirer",
      link: "",
      content: "Selam! Sending greetings from Ethiopia.",
      country: "Ethiopia",
    },
    {
      author: "Dakar Resident",
      link: "https://example.com/senegal",
      content: "Salam! Greetings from Senegal.",
      country: "Senegal",
    },
    {
      author: "Algerian Friend",
      link: "",
      content: "As-salamu alaykum! Visiting from Algeria.",
      country: "Algeria",
    },
    {
      author: "Ali",
      link: "",
      content: "Sa'adt bi liqa'ak",
      country: "United Arab Emirates",
    },
    {
      author: "Taiwanese Visitor",
      link: "https://example.com/taiwan",
      content:
        "你好 (Nǐ hǎo)! This guestbook is as impressive as the view from Taipei 101.",
      country: "Taiwan",
    },
    {
      author: "Peruvian Visitor",
      link: "https://example.com/peru",
      content:
        "¡Hola! A pleasure to sign your guestbook. As breathtaking as the sight of Machu Picchu.",
      country: "Peru",
    },
    {
      author: "Serbian Guest",
      link: "https://example.com/serbia",
      content: "Greetings from Serbia!",
      country: "Serbia",
    },
    {
      author: "Greek Nomad",
      link: "https://example.com/greece",
      content:
        "From the Aegean with admiration. Your guestbook feels like a quiet Santorini evening.",
      country: "Greece",
    },
    {
      author: "Thai Traveler",
      link: "https://example.com/thailand",
      content:
        "Warm regards from Bangkok. This site radiates the serenity of a Thai sunrise.",
      country: "Thailand",
    },
    {
      author: "Singapore Soul",
      link: "https://example.com/singapore",
      content:
        "Tidy, bright, efficient—your site reminds me of Orchard Road at its best.",
      country: "Singapore",
    },
    {
      author: "Hungarian Guest",
      link: "https://example.com/hungary",
      content:
        "As delightful as a stroll by the Danube. Greetings from Budapest.",
      country: "Hungary",
    },
    {
      author: "Belgian Friend",
      link: "https://example.com/belgium",
      content: "Waffles, art, and this website—Belgium approves.",
      country: "Belgium",
    },
    {
      author: "Austrian Visitor",
      link: "https://example.com/austria",
      content:
        "Greetings from Vienna. This site has more harmony than a Mozart concerto.",
      country: "Austria",
    },
    {
      author: "Kiwi Coder",
      link: "https://example.com/nz",
      content:
        "Kia ora from Aotearoa. Minimal and clear—like the Southern Alps.",
      country: "New Zealand",
    },
    {
      author: "South Sudanese Voice",
      link: "https://example.com/southsudan",
      content: "From Juba to your guestbook—connection feels good.",
      country: "South Sudan",
    },
    {
      author: "Israeli Wanderer",
      link: "https://example.com/israel",
      content: "Shalom from Tel Aviv. This site flows like hummus and pita.",
      country: "Israel",
    },
    {
      author: "Czech Visitor",
      link: "https://example.com/czech",
      content: "From Prague’s quiet corners to your digital one—cheers.",
      country: "Czech Republic",
    },
    {
      author: "Finnish Observer",
      link: "https://example.com/finland",
      content: "Calm, focused, refined. Your guestbook is a Lapland breeze.",
      country: "Finland",
    },
    {
      author: "Iraqi Reader",
      link: "https://example.com/iraq",
      content: "Peace from Baghdad. You've built something thoughtful here.",
      country: "Iraq",
    },
    {
      author: "Slovak Guest",
      link: "https://example.com/slovakia",
      content: "Simple. Clear. Good work from Bratislava.",
      country: "Slovakia",
    },
    {
      author: "Romanian Coder",
      link: "https://example.com/romania",
      content: "Salutări din România. Compact and smooth—nice touch.",
      country: "Romania",
    },
    {
      author: "Lebanese Wanderer",
      link: "https://example.com/lebanon",
      content: "From the Cedars to the code—this place has soul.",
      country: "Lebanon",
    },
    {
      author: "Sri Lankan Mind",
      link: "https://example.com/srilanka",
      content: "Your site feels like a walk near Sigiriya at dawn. Peaceful.",
      country: "Sri Lanka",
    },
    {
      author: "Nepali Visitor",
      link: "https://example.com/nepal",
      content: "From Kathmandu with respect. This guestbook has good spirit.",
      country: "Nepal",
    },
    {
      author: "Jordanian Friend",
      link: "https://example.com/jordan",
      content: "Greetings from Amman. Simple things done well—like mansaf.",
      country: "Jordan",
    },
    {
      author: "Zimbabwean Guest",
      link: "https://example.com/zimbabwe",
      content: "From the lands of Vic Falls—your site speaks quietly but well.",
      country: "Zimbabwe",
    },
    {
      author: "Palestinian Visitor",
      link: "https://example.com/palestine",
      content:
        "From Ramallah to your world—thanks for making a space worth pausing in.",
      country: "Palestine",
    },
  ]);
}
