import { db, GuestBook } from "astro:db";

// https://astro.build/db/seed
export default async function seed() {
  await db.insert(GuestBook).values([
    {
      author: "Alice Johnson",
      link: "https://alice.dev",
      content: "Love your work, keep it up!",
      country: "United States",
    },
    {
      author: "Ravi Kumar",
      link: "https://rkumar.blog",
      content: "Very interesting guestbook concept!",
      country: "India",
    },
    {
      author: "Li Wei",
      link: "",
      content: "Greetings from China!",
      country: "China",
    },
    {
      author: "Bob Smith",
      link: "",
      content: "Just dropping by to say hi!",
      country: "United Kingdom",
    },
    {
      author: "Gideon",
      link: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
      content: "This is so cool!",
      country: "Canada",
    },
    {
      author: "Frank Miller",
      link: "",
      content: "This guestbook idea is awesome!",
      country: "Germany",
    },
    {
      author: "Isabella Rossi",
      link: "https://isabellar.com",
      content: "Amazing job from Brazil!",
      country: "Brazil",
    },
    {
      author: "Eva Williams",
      link: "https://evaw.design",
      content: "As a designer, I really appreciate the aesthetics here.",
      country: "France",
    },
    {
      author: "Olga Petrova",
      link: "",
      content: "Nice website design from Russia.",
      country: "Russia",
    },
    {
      author: "Charlie Adams",
      link: "https://charlieadams.blog",
      content: "Great site from Down Under!",
      country: "Australia",
    },
    {
      author: "Carlos Garcia",
      link: "https://cgarcia.mx",
      content: "Saludos desde México!",
      country: "Mexico",
    },
    {
      author: "Kenji Tanaka",
      link: "https://ktanaka.jp",
      content: "Inspiring work from Japan!",
      country: "Japan",
    },
    {
      author: "Maria Santos",
      link: "",
      content: "Visiting from the Philippines!",
      country: "Philippines",
    },
    {
      author: "Budi Hartono",
      link: "https://budi.id",
      content: "Keep up the great work!",
      country: "Indonesia",
    },
    {
      author: "Marco Rossi",
      link: "",
      content: "Ciao! Love the guestbook.",
      country: "Italy",
    },
    {
      author: "David Umoru",
      link: "https://davidumoru.me",
      content: "Hey, welcome to my guestbook!",
      country: "Nigeria",
    },
    {
      author: "Ahmed Khan",
      link: "https://akhan.pk",
      content: "Greetings from Pakistan!",
      country: "Pakistan",
    },
    {
      author: "Ayse Yilmaz",
      link: "",
      content: "Merhaba from Turkey!",
      country: "Turkey",
    },
    {
      author: "Grace Lee",
      link: "https://gracecodes.dev",
      content: "Nice work! Looking forward to more updates from South Korea.",
      country: "South Korea",
    },
    {
      author: "Sofia Lopez",
      link: "https://slopez.es",
      content: "Hola! Impressive site from Spain.",
      country: "Spain",
    },
    {
      author: "Jan Jansen",
      link: "",
      content: "Groeten uit Nederland!",
      country: "Netherlands",
    },
    {
      author: "Thabo Muller",
      link: "https://tmuller.za",
      content: "Cool guestbook feature from South Africa!",
      country: "South Africa",
    },
    {
      author: "Nguyen Van An",
      link: "",
      content: "Xin chào from Vietnam!",
      country: "Vietnam",
    },
    {
      author: "Fatima Ali",
      link: "https://fali.eg",
      content: "Visiting from Egypt.",
      country: "Egypt",
    },
    {
      author: "Rahim Ahmed",
      link: "",
      content: "Good job on the site from Bangladesh.",
      country: "Bangladesh",
    },
    {
      author: "Ivan Ivanov",
      link: "https://ivanov.ua",
      content: "Sending support from Ukraine!",
      country: "Ukraine",
    },
    {
      author: "Abdullah Al-Fahad",
      link: "",
      content: "Salam from Saudi Arabia!",
      country: "Saudi Arabia",
    },
    {
      author: "Maria Fernandez",
      link: "https://mfernandez.ar",
      content: "Interesting project from Argentina!",
      country: "Argentina",
    },
    {
      author: "Piotr Nowak",
      link: "",
      content: "Cześć! Nice guestbook from Poland.",
      country: "Poland",
    },
    {
      author: "Siti Aminah",
      link: "https://siti.my",
      content: "Great to see projects like this from Malaysia!",
      country: "Malaysia",
    },
    {
      author: "Visitor From Norway",
      link: "",
      content: "Beautiful design, greetings from Norway!",
      country: "Norway",
    },
    {
      author: "Island Visitor",
      link: "https://example.com/turksandcaicos",
      content: "Lovely guestbook! - Turks and Caicos",
      country: "Turks and Caicos",
    },
    {
      author: "Seychelles Guest",
      link: "",
      content: "Signing in from Seychelles!",
      country: "Seychelles",
    },
    {
      author: "Croatian Friend",
      link: "https://example.com/croatia",
      content: "Pozdrav iz Hrvatske! (Greetings from Croatia!)",
      country: "Croatia",
    },
    {
      author: "Portuguese Explorer",
      link: "",
      content: "Olá! Great site.",
      country: "Portugal",
    },
    {
      author: "Swedish Supporter",
      link: "https://example.com/sweden",
      content: "Hej från Sverige!",
      country: "Sweden",
    },
    {
      author: "Moroccan Traveler",
      link: "",
      content: "Greetings from Morocco.",
      country: "Morocco",
    },
    {
      author: "Colombian Connection",
      link: "https://example.com/colombia",
      content: "Saludos desde Colombia!",
      country: "Colombia",
    },
    {
      author: "Chilean Observer",
      link: "",
      content: "Hola from Chile!",
      country: "Chile",
    },
    {
      author: "Irish Visitor",
      link: "https://example.com/ireland",
      content: "Top o' the mornin'! Nice guestbook.",
      country: "Ireland",
    },
    {
      author: "Mauritius Fan",
      link: "",
      content: "Visiting from Mauritius!",
      country: "Mauritius",
    },
    {
      author: "Swiss Guest",
      link: "https://example.com/switzerland",
      content: "Grüezi! Signing from Switzerland.",
      country: "Switzerland",
    },
    {
      author: "Cameroon Explorer",
      link: "https://example.com/cameroon",
      content: "Bonjour! Signing in from Cameroon.",
      country: "Cameroon",
    },
    {
      author: "Safari Enthusiast",
      link: "",
      content: "Jambo! Greetings from beautiful Kenya.",
      country: "Kenya",
    },
    {
      author: "Accra Visitor",
      link: "https://example.com/ghana",
      content: "Akwaaba! Enjoying my time in Ghana.",
      country: "Ghana",
    },
    {
      author: "Lalibela Admirer",
      link: "",
      content: "Selam! Sending greetings from Ethiopia.",
      country: "Ethiopia",
    },
    {
      author: "Dakar Resident",
      link: "https://example.com/senegal",
      content: "Salam! Greetings from Senegal.",
      country: "Senegal",
    },
    {
      author: "Algerian Friend",
      link: "",
      content: "As-salamu alaykum! Visiting from Algeria.",
      country: "Algeria",
    },
  ]);
}
